### ISSUE TITLE
Coinbase : Callbacks to chcek if something succeeded or not

### ISSUE THREAD

**Issue by MaruthiPrasadA** [bchavez/Coinbase#14]
As we are unable to set up Sandbox for Coinbase since there are many exceptions with our piece of code, we are setting up Live Coinbase setup , in this we need some help from you on whether we are going correct way or not. 

And with respect to live coinbase environment, i have below question:
Q1 : Are the 4 Redirect URLs required ? If mentioned all the 4 URLs, how will the flow in the application?
CallbackUrl = "http://localhost:50430/Checkout/Confirm",
CancelUrl = "http://localhost:50430/Checkout/Cancel",
InfoUrl = "http://localhost:50430/Checkout/Info",
SuccessUrl = "http://localhost:50430/Checkout/Success",

And if possible share the Sandbox sample in https://dotnetfiddle.net

Thanks

**Comment by bchavez** [comment]
I think this has been resolved now, closing the issue. thanks.

**Comment by MaruthiPrasadA** [comment]
Waiting for the reply. Please guide us to achieve the above REAl TIME scenario.

**Comment by bchavez** [comment]
I'm not sure what "guidance" you want. Yes, it looks OK. Did you try it?

**Comment by MaruthiPrasadA** [comment]
Yes. We are ready to publish and test it in production BUT since it is LIVE API code and to test we need to have REAL BTC to test.(we have BTC).

**Comment by bchavez** [comment]
What *specific* guidance do you want me to provide?

The ***best*** guidance I can give you is:
http://c2.com/cgi/wiki?TrialAndErrorProgramming

***Try it.*** If your afraid of using it on a ***LIVE*** system, then get the **Sandbox** to work. If you cannot get **Sandbox** to work, then invest some time in figuring out **why** it does not work.

I can help you with **specific** questions with respect to the code base in this repository. Beyond that, you will need to figure out why **sandbox** is not working.

**Comment by MaruthiPrasadA** [comment]
OK. We will try our hand again on Sandbox. Can you please confirm, with that Sandbox can we test the above scenarios ?

**Comment by bchavez** [comment]
Whatever you do on LIVE you should be able to do on SANDBOX. If you cannot, then it is a problem with your setup. 1) Firewall, 2) Sandbox Account ./ API KEY, 3) Coding Error, 4) Coinbase, 5) This API.

If you cannot find the **root** cause of problem, then use Google and spend some time **researching** your problem before asking for help. After you've exhausted all your options, then post an issue with the appropriate people with all relevant information; IE: Stack Traces / Code, Error Messages, etc.

***Please keep-in-mind***, I do not get **paid** for answering your Coinbase questions nor do I get paid for this open-source work. Therefore, my time is limited and I cannot provide you with "general guidance". There is ample documentation + source code examples with unit tests. You should be able to pull together a working application. If you're not familiar with basic debugging, application troubleshooting, or software design, then please find someone that understands these concepts to help you build application.

Please do not waste my time with "confirming" yes/no questions ... the best way is to ***simply, try it***.

**Comment by MaruthiPrasadA** [comment]
Thanks.
