### ISSUE TITLE
iFrame -  Stopped working within website suddenly

### ISSUE THREAD

**Issue by MaruthiPrasadA** [bchavez/Coinbase#15]
@bchavez : 
Today we are getting strange issue, even with Live implementation for Coinbase, with iFrame binding in our website payment page. Instead of displaying the bitcoin address on which bitcoin payment accepted, it is displaying below message:

X This content cannot be displayed in a frame
To help protect the security of information you enter into this website, the publisher of this content does not allow it to be displayed in a frame.

What you can try:
Open this content in a new window

Attached the Actual and Strange behaviors of coinbase iFrame recently.

Please guide us to get over this behavior. Thanks in advance.
![coinbase actual iframe](https://cloud.githubusercontent.com/assets/2277305/8177384/e08d65c4-1421-11e5-9ad4-4aa75d56a3dd.png)
![coinbase iframe](https://cloud.githubusercontent.com/assets/2277305/8177385/e08f7c56-1421-11e5-9a99-5b3479b36420.png)

**Comment by bchavez** [comment]
Did you try doing what the message describes?

As the error message says..... "To help protect the security of information you enter into this website, the publisher of this content does not allow it to be displayed in a frame."

You probably cannot embed the Bitcoin checkout in an IFRAME. Try the whole process without an IFRAME.

**Comment by MaruthiPrasadA** [comment]
@bchavez :

 Thanks for the reply. We got confirmation from Coinbase that the problem is at their end and it got rectified. Just now we tested and it is working without single piece of code change.

 Once again, thank you @bchavez  for your responses.

**Comment by bchavez** [comment]
Great, glad you got it working. I will close the issue now.
