### ISSUE TITLE
Coinbase : Callbacks status " Expired" 

### ISSUE THREAD

**Issue by MaruthiPrasadA** [bchavez/Coinbase#16]
@bchavez:

In the current Coinbase API, under Coinbase\ObjectModel\Status.cs should have this option also as if the Coinbase didn't receive any payments for the Order within 10 minutes of its generation. Means if an "Expired" Order receives a payment, the Order will remain "Expired" but will have Mispayments associated with it. 

And moreover Coinbase will not have sent the merchant any order-completed callbacks for "Expired" orders so if the merchant is counting on these callbacks to complete the order fulfilment or refund process, they'll have to MANUALLY perform this step.

Please think over it and if it should be there, then update the API.

**Comment by bchavez** [comment]
Thank you. I've added `Expired` to `Status` enum. I've also pushed v0.3.11 should be available on NuGet soon. Any other SDK API troubles let me know and I'll be happy to help.
