### ISSUE TITLE
Coinbase : Issue while checking Order Status using API's GetOrder method

### ISSUE THREAD

**Issue by MaruthiPrasadA** [bchavez/Coinbase#17]
As we recently completed Coinbase API integration in our website and tested locally and PRODUCTION also for the iFrame generation and integration within our website, it worked good. But suddenly raising exception when we are trying to get the Order status in the code using API's api.Getorder() . To cross check the behavior in dev environment locally, the issue is there too. 

{ 
string inventCustomID = "CustID" ;---testing 
var api = new CoinbaseApi(apiKey: "LIVEKEYID", apiSecret: "LIVEKEYSECRET"); 
var orderResult = api.GetOrder(inventCustomID);
..........
} 
No clue on this sudden and strange behavior. Attached the screen-shots for this behavior. Please guide us to get over this behaviour.
![coinbase api exception](https://cloud.githubusercontent.com/assets/2277305/8471499/6c15fe9e-20b6-11e5-8333-ecfd68a168d3.png)
![coinbase api exception2](https://cloud.githubusercontent.com/assets/2277305/8471500/6c19b944-20b6-11e5-8518-99b6d0d4ca96.png)

Thanks,MaruthiPrasad A

**Comment by bchavez** [comment]
@MaruthiPrasadA 

What version of the coinbase lib are you using?

**Comment by bchavez** [comment]
![screen417](https://cloud.githubusercontent.com/assets/478118/8471538/2387ab86-204e-11e5-8c75-93eeb69265b5.png)

**Comment by MaruthiPrasadA** [comment]
![image](https://cloud.githubusercontent.com/assets/2277305/8477143/87098598-20e5-11e5-8ed2-07465c13baaf.png)

**Comment by bchavez** [comment]
@MaruthiPrasadA 

You're using an old version. You previous issue #16 was filed and fixed. Please check Nuget for latest version `0.3.11`. https://www.nuget.org/packages/Coinbase/

**Comment by MaruthiPrasadA** [comment]
Thanks for the reply.

**Comment by MaruthiPrasadA** [comment]
But my observation is that the payment went good some times and failing with this exception some other times and that to this is recently.

**Comment by bchavez** [comment]
@MaruthiPrasadA Update your nuget package to `0.3.11` you will get the same error again when the condition is met again.
