### ISSUE TITLE
Coinbase : Issue with upgrade to latest version 0.3.11.

### ISSUE THREAD

**Issue by MaruthiPrasadA** [bchavez/Coinbase#18]
As suggested we tried to pull the coinbase latest using Nuget for version 0.3.11, we are experiencing the below issue while creating payment button programmaticlly for Live like below : 
  var api = new CoinbaseApi(CoinbaseApiKey,CoinbaseApiSecret,useSandbox:false,proxy:null);    
                var paymenRequest = new ButtonRequest
                {
                    Name = "Sample Text",
                    Currency = currencySign,
                    Price = total,
                    Type = ButtonType.BuyNow,
                    Custom = inventID,
                    Description = "Sample Desc",
                    Style = ButtonStyle.CustomLarge,
                    CallbackUrl = CallbackURL,
                    CancelUrl = CancelURL,
                    InfoUrl = InfoURL,
                    SuccessUrl = SuccessURL,
                };
      var buttonResponse = api.RegisterButton(paymenRequest);
![coinbase latest upgrade issue](https://cloud.githubusercontent.com/assets/2277305/8569871/83e2725e-2599-11e5-8833-7277b209fa9b.png)

**Comment by bchavez** [comment]
@MaruthiPrasadA 

I've pushed some changes via Nuget; could you please check if the latest version `v0.3.12` resolves your issue? Thanks.

**Comment by MaruthiPrasadA** [comment]
@bchavez 

 Thanks for your efforts. I pulled the latest v0.3.12 and tested with my app, it is working good.
