### ISSUE TITLE
Nuget Package Newtonsoft.Json Dependency Version

### ISSUE THREAD

**Issue by thequantumguy01** [bchavez/Coinbase#23]
Any chance the package could be updated to allow use with Newtsonsoft.Json version 8? Currently the version requirement is (>= 7.0.0 && < 8.0.0)

**Comment by bchavez** [comment]
Sure. No problem, I will try to get to this when I get home. Currently on vacation at the moment.

**Comment by bchavez** [comment]
@thequantumguy01 Your issue should be fixed in `v2.0.6`. Hope that helps!
