### ISSUE TITLE
Buy Coins

### ISSUE THREAD

**Issue by EDelfosse** [bchavez/Coinbase#29]
I am confused as to how to buy coins with this API. Would I just use the SendRequest with the parameters in the data section? How would I format these parameters?
Thanks!

**Comment by bchavez** [comment]
Hi @EDelfosse ,

You'll have to read the documentation here: https://developers.coinbase.com/api/v2#place-buy-order

From the looks of it, yeah, you'd need to use `SendRequest` to "place a buy order" with the correct parameters.

There should be examples of how to create requests & parameters to API endpoints in the unit test source. The unit test examples are different from what you're trying to achieve but the general idea is the same.

Also, I have not used this library to "buy/purchase coins". My primary use case for this library is a checkout gateway API. IE: where people already have coins and I want to accept them as payment for a product or service.

If you have other questions, you'll probably want to talk to the people at api@coinbase.com. Try to get a general idea of what you need to do. IE: what API endpoints are important in what you're trying to achieve etc,... then try to create them in C# with this library.

Also, I don't work for Coinbase, so I can't help much with "how do I xyz?" but if you find bugs or issues with this C# code library, feel free to raise them as an issue.

Thanks,
Brian
