### ISSUE TITLE
Test Wont Run

### ISSUE THREAD

**Issue by granthoff1107** [bchavez/Coinbase#36]
Not sure why but the tests still wont run.
![testwontrun](https://user-images.githubusercontent.com/13307037/48236778-c33b3300-e391-11e8-92ee-8f1f11518528.gif)

**Comment by bchavez** [comment]
Hi Grant,

Try pulling latest `/master` and try again. 3c786a4 should fix it. Normally, I run tests with ReSharper's built in test runner, not necessarily Visual Studio's test runner. I just now added the `NUnit3TestAdapter` NuGet reference; so it should fix your issue.

Thanks,
Brian

:zap: :runner: ***["I was struck by lighting. Walkin' down the street..."](https://www.youtube.com/watch?v=iypUpv9xelg)***
