### ISSUE TITLE
OAuth Auth Refresh Tokens

### ISSUE THREAD

**Issue by granthoff1107** [bchavez/Coinbase#40]
I'll create a pull request for this this weekend, but lets discuss the specs,
Basically when a token expired 2 things should happen.

    1. The Token internally refresh and replays the last request.
    2. We need a call back or an external event so the user can update their user information appropriately.

Specs:

    When a user's token expires the server will return 401 Error with an id  expired_token, 
    Send a request to the Coinbase OAuthEndpoint 

        POST https://api.coinbase.com/oauth/token
        Body: {
             refresh_token  : "34t703948twdfuhgsdofigheiosfghsoidhgier"
             grant_type: "refresh_token"
        }

The Server will response:

 "access_token": "regjworigjwoerigjpworegjodspfjgospfijgweoprijg",
    "token_type": "bearer",
    "expires_in": 7200,
    "refresh_token": "lkdfgadlkgheaklrherthiuhidsuhidfuh",
    "scope": "wallet:accounts:read wallet:addresses:read",
    "created_at": 1541870695

**Comment by bchavez** [comment]
This should be done now with the latest beta.

https://www.nuget.org/packages/Coinbase/5.0.0-beta-5

See docs for details:
https://github.com/bchavez/Coinbase#authentication-details

Thanks again Grant for the help!

-Brian

**Comment by granthoff1107** [comment]
Any luck on merging the latest pull request for refresh tokens?
