### ISSUE TITLE
Can't make a pull request

### ISSUE THREAD

**Issue by granthoff1107** [bchavez/Coinbase#42]
For some reason github won't allow me to make a pull request.  I forgot to call the on token refresh and the config should be async 

https://github.com/granthoff1107/Coinbase/tree/AutoRefreshTokens

**Comment by bchavez** [comment]
Your PR is already active.

![chrome_2382](https://user-images.githubusercontent.com/478118/48669387-891c1080-eab8-11e8-8c64-08dfac92b3cc.png)

Any more commits to your `granthoff/AutoRefreshTokens` branch will automatically be included in the active PR.

**Comment by bchavez** [comment]
Also, quick tip:

Always click "Files changed" tab to see the to see the most up to date changes that the PR will deliver.

![chrome_2387](https://user-images.githubusercontent.com/478118/48669452-b0271200-eab9-11e8-82da-0e5cd84625e4.png)
