### ISSUE TITLE
Access to the Raw response from the API

### ISSUE THREAD

**Issue by granthoff1107** [bchavez/Coinbase#55]
There is no way to access the request made by the api. e.g if I would like to obtain the response code and the Errors it difficult. e.g

If I were to make a request to obtain send money:

    var resp = await this._coinbaseOAuthClient.AllowAnyHttpStatus()
                            .WithHeader("CB-2FA-TOKEN", paymentTransaction.TwoFactorCode)
                            .AllowAnyHttpStatus()
                                        .Transactions
                                        .SendMoneyAsync(paymentTransaction.AccountId, transaction);

The response returns a 402 requires payment.   But if I allow any http status I'm not sure of a way to obtain the response or have access to the raw request.

If I were to wrap not allow any httpstatus:

    try{
        var resp = await this._coinbaseOAuthClient.AllowAnyHttpStatus()
                            .WithHeader("CB-2FA-TOKEN", paymentTransaction.TwoFactorCode)
                            .AllowAnyHttpStatus()
                                        .Transactions
                                        .SendMoneyAsync(paymentTransaction.AccountId, transaction);
    }
    catch (FlurlHttpException ex) {
         
    }
    
There's no easy way to obtain the error inside of the response.

**Comment by bchavez** [comment]
* Can you post the **full** trace of the HTTP request ***and*** response with raw body payloads and headers from Fiddler?
* Does the `.Errors` array not have the error you're looking for?
https://github.com/bchavez/Coinbase/blob/34946ddf75000cf6d2cc9007a090737d41d561ff/Source/Coinbase/Models/JsonResponse.cs#L56

**Comment by granthoff1107** [comment]
I cant post the trace it has too much sensitive data. But what I'm trying to say is that if you allow any httpstatus code wont have any access to the request,  because we only return the data returned by the request.If you allow flurl to throw the exception will contain the request being made inside of it.  In most cases you should be able to determine the error from the errors property.But if for some reason there is an with no errors property you will have no idea what occured,E.g 500 or rate limit etc.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Brian Chavez <notifications@github.com> Date: 3/20/19  7:47 PM  (GMT-05:00) To: bchavez/Coinbase <Coinbase@noreply.github.com> Cc: granthoff1107 <granthoff1107@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bchavez/Coinbase] Access to the Raw response from the API (#55) 
Can you post the full trace of the HTTP request and response with raw body payloads and headers from Fiddler?
Does the .Errors array not have the error you're looking for?
https://github.com/bchavez/Coinbase/blob/34946ddf75000cf6d2cc9007a090737d41d561ff/Source/Coinbase/Models/JsonResponse.cs#L56


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bchavez/Coinbase","title":"bchavez/Coinbase","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bchavez/Coinbase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bchavez in #55: * Can you post the **full** trace of the HTTP request ***and*** response with raw body payloads and headers from Fiddler?\r\n* Does the `.Errors` array not have the error you're looking for?\r\nhttps://github.com/bchavez/Coinbase/blob/34946ddf75000cf6d2cc9007a090737d41d561ff/Source/Coinbase/Models/JsonResponse.cs#L56\r\n\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/bchavez/Coinbase/issues/55#issuecomment-475070797"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bchavez/Coinbase/issues/55#issuecomment-475070797",
"url": "https://github.com/bchavez/Coinbase/issues/55#issuecomment-475070797",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bchavez** [comment]
Hi Grant,

You can also replace the sensitive data with random data and post it here. Or, additionally, you can send it privately to my email. I just need some general idea of HTTP interaction with the code to better understand the problem with the request/response mechanism; ideally, so I can write a unit test.

I don't usually like changing code unless I understand 100% the reasons why I'm changing it. Unfortunately, I'm reading what you're saying but I cannot translate English words into any actual debug session and provide solutions without seeing the HTTP transport mechanisms in play to reproduce the same feeling of frustration you're encountering.

As a work around, perhaps you can inherit from `CoinbaseApi` and instead do the interaction manually: 

https://github.com/bchavez/Coinbase/blob/34946ddf75000cf6d2cc9007a090737d41d561ff/Source/Coinbase/CoinbaseClient.Transactions.cs#L94-L98

Also, this might help breaking up the steps in a piecemeal steps:
https://stackoverflow.com/questions/43488710/getting-response-header/53514668#53514668

Let me know.

**Comment by granthoff1107** [comment]
Sorry for the confusion, to simplify how do how do you get the httpstatuscode the coinbase wrapper doesn't contain the responseSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Brian Chavez <notifications@github.com> Date: 3/20/19  9:58 PM  (GMT-05:00) To: bchavez/Coinbase <Coinbase@noreply.github.com> Cc: granthoff1107 <granthoff1107@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bchavez/Coinbase] Access to the Raw response from the API (#55) Hi Grant,
You can also replace the sensitive data with random data and post it here. Or, additionally, you can send it privately to my email. I just need some general idea of HTTP interaction with the code to better understand the problem with the request/response mechanism; ideally, so I can write a unit test.
I don't usually like changing code unless I understand 100% the reasons why I'm changing it. Unfortunately, I'm reading what you're saying but I cannot translate English words into any actual debug session and provide solutions without seeing the HTTP transport mechanisms in play to reproduce the same feeling of frustration you're encountering.
As a work around, perhaps you can inherit from CoinbaseApi and instead do the interaction manually:
https://github.com/bchavez/Coinbase/blob/34946ddf75000cf6d2cc9007a090737d41d561ff/Source/Coinbase/CoinbaseClient.Transactions.cs#L94-L98
Also, this might help breaking up the steps in a piecemeal steps:
https://stackoverflow.com/questions/43488710/getting-response-header/53514668#53514668
Let me know.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bchavez/Coinbase","title":"bchavez/Coinbase","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bchavez/Coinbase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bchavez in #55: Hi Grant,\r\n\r\nYou can also replace the sensitive data with random data and post it here. Or, additionally, you can send it privately to my email. I just need some general idea of HTTP interaction with the code to better understand the problem with the request/response mechanism; ideally, so I can write a unit test.\r\n\r\nI don't usually like changing code unless I understand 100% the reasons why I'm changing it. Unfortunately, I'm reading what you're saying but I cannot translate English words into any actual debug session and provide solutions without seeing the HTTP transport mechanisms in play to reproduce the same feeling of frustration you're encountering.\r\n\r\nAs a work around, perhaps you can inherit from `CoinbaseApi` and instead do the interaction manually: \r\n\r\nhttps://github.com/bchavez/Coinbase/blob/34946ddf75000cf6d2cc9007a090737d41d561ff/Source/Coinbase/CoinbaseClient.Transactions.cs#L94-L98\r\n\r\nAlso, this might help breaking up the steps in a piecemeal steps:\r\nhttps://stackoverflow.com/questions/43488710/getting-response-header/53514668#53514668\r\n\r\nLet me know."}],"action":{"name":"View Issue","url":"https://github.com/bchavez/Coinbase/issues/55#issuecomment-475090740"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bchavez/Coinbase/issues/55#issuecomment-475090740",
"url": "https://github.com/bchavez/Coinbase/issues/55#issuecomment-475090740",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bchavez** [comment]
Hey Grant,

If you want the status code, I don't think there's two ways about it. I think you'll have to split up the call and do things manually as shown below:
```csharp
var client = new CoinbaseClient();
var accountId = "aaa";
var txn = new CreateTransaction();

var task = this.client.Config.ApiUrl
   .AppendPathSegments("accounts", accountId, "transactions")
   .WithClient(client)
   .PostJsonAsync(txn);

var response = await task;

var httpCode = response.StatusCode;

var model = await task.ReceiveJson<Response<Transaction>>();
```

**Comment by granthoff1107** [comment]
Thanks, maybe in future versions we could store the http call in the wrapper.  I haven't come across a time when I 100 percent need it, but for certain things I'd rather rely on httostatus code rather than parsing the errorsSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Brian Chavez <notifications@github.com> Date: 3/21/19  12:36 AM  (GMT-05:00) To: bchavez/Coinbase <Coinbase@noreply.github.com> Cc: granthoff1107 <granthoff1107@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bchavez/Coinbase] Access to the Raw response from the API (#55) Hey Grant,
If you want the status code, I don't think there's two ways about it. I think you'll have to split up the call and do things manually as shown below:
var client = new CoinbaseClient();
var accountId = "aaa";
var txn = new CreateTransaction();

var task = this.client.Config.ApiUrl
   .AppendPathSegments("accounts", accountId, "transactions")
   .WithClient(client)
   .PostJsonAsync(txn);

var response = await task;

var httpCode = response.StatusCode;

var model = await task.ReceiveJson<Response<Transaction>>();

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bchavez/Coinbase","title":"bchavez/Coinbase","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bchavez/Coinbase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bchavez in #55: Hey Grant,\r\n\r\nIf you want the status code, I don't think there's two ways about it. I think you'll have to split up the call and do things manually as shown below:\r\n```csharp\r\nvar client = new CoinbaseClient();\r\nvar accountId = \"aaa\";\r\nvar txn = new CreateTransaction();\r\n\r\nvar task = this.client.Config.ApiUrl\r\n   .AppendPathSegments(\"accounts\", accountId, \"transactions\")\r\n   .WithClient(client)\r\n   .PostJsonAsync(txn);\r\n\r\nvar response = await task;\r\n\r\nvar httpCode = response.StatusCode;\r\n\r\nvar model = await task.ReceiveJson\u003cResponse\u003cTransaction\u003e\u003e();\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/bchavez/Coinbase/issues/55#issuecomment-475111106"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bchavez/Coinbase/issues/55#issuecomment-475111106",
"url": "https://github.com/bchavez/Coinbase/issues/55#issuecomment-475111106",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bchavez** [comment]
Here's another way to do it:

```csharp
var accountId = "aaa";
var txn = new CreateTransaction();

HttpResponseMessage response = null;
this.client.Configure(cf =>
   {
      cf.AfterCall = http =>
         {
            response = http.Response;
         };
   });

var model = await client
   .AllowAnyHttpStatus()
   .Transactions
   .SendMoneyAsync(accountId, txn);

var httpCode = response.StatusCode;
```

**Comment by bchavez** [comment]
And another way...
```csharp
var accountId = "aaa";
var txn = new CreateTransaction();

var model = await client
   .HoistResponse(out var responseGetter)
   .AllowAnyHttpStatus()
   .Transactions
   .SendMoneyAsync(accountId, txn);

var response = responseGetter();

response.StatusCode;
```
Using this extension:
```csharp
public static class HoistExtensionsForCoinbaseClient
{
   public static CoinbaseClient HoistResponse(this CoinbaseClient client, out Func<HttpResponseMessage> responseGetter)
   {
      HttpResponseMessage msg = null;
      client.Configure(cf =>
         {
            cf.AfterCall = http =>
               {
                  msg = http.Response;
               };
         });

      responseGetter = () => msg;
      return client;
   }
}
```

**Comment by granthoff1107** [comment]
Thanks the last one looks perfectSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Brian Chavez <notifications@github.com> Date: 3/21/19  1:27 AM  (GMT-05:00) To: bchavez/Coinbase <Coinbase@noreply.github.com> Cc: granthoff1107 <granthoff1107@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bchavez/Coinbase] Access to the Raw response from the API (#55) And another way...
var accountId = "aaa";
var txn = new CreateTransaction();

var model = await client
   .HoistResponse(out var responseGetter)
   .AllowAnyHttpStatus()
   .Transactions
   .SendMoneyAsync(accountId, txn);

var response = responseGetter();

response.StatusCode;
Using this extension:
public static class HoistExtensionsForCoinbaseClient
{
   public static CoinbaseClient HoistResponse(this CoinbaseClient client, out Func<HttpResponseMessage> responseGetter)
   {
      HttpResponseMessage msg = null;
      client.Configure(cf =>
         {
            cf.AfterCall = http =>
               {
                  msg = http.Response;
               };
         });

      responseGetter = () => msg;
      return client;
   }
}

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bchavez/Coinbase","title":"bchavez/Coinbase","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bchavez/Coinbase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bchavez in #55: And another way...\r\n```csharp\r\nvar accountId = \"aaa\";\r\nvar txn = new CreateTransaction();\r\n\r\nvar model = await client\r\n   .HoistResponse(out var responseGetter)\r\n   .AllowAnyHttpStatus()\r\n   .Transactions\r\n   .SendMoneyAsync(accountId, txn);\r\n\r\nvar response = responseGetter();\r\n\r\nresponse.StatusCode;\r\n```\r\nUsing this extension:\r\n```csharp\r\npublic static class HoistExtensionsForCoinbaseClient\r\n{\r\n   public static CoinbaseClient HoistResponse(this CoinbaseClient client, out Func\u003cHttpResponseMessage\u003e responseGetter)\r\n   {\r\n      HttpResponseMessage msg = null;\r\n      client.Configure(cf =\u003e\r\n         {\r\n            cf.AfterCall = http =\u003e\r\n               {\r\n                  msg = http.Response;\r\n               };\r\n         });\r\n\r\n      responseGetter = () =\u003e msg;\r\n      return client;\r\n   }\r\n}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/bchavez/Coinbase/issues/55#issuecomment-475116928"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bchavez/Coinbase/issues/55#issuecomment-475116928",
"url": "https://github.com/bchavez/Coinbase/issues/55#issuecomment-475116928",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
