### ISSUE TITLE
Creating a new invoice

### ISSUE THREAD

**Issue by chuksgpfr** [bchavez/Coinbase#56]
The implementation i have read is confusing, how do i create an invoice with asp.net core. 
PS: Dynamic invoice

**Comment by bchavez** [comment]
If you're looking to charge a customer something, you might want to look at **Coinbase.Commerce** here:
https://github.com/bchavez/Coinbase.Commerce

The **Coinbase** library here is mostly for account/wallet manipulation of **Coinbase** accounts; not so much for charging customers an invoice. 

If you use this library, you have to make the invoice yourself (code it and host it) and ask permission to access the customer's Coinbase account and initiate the payment manually with the wallet send/receive APIs for the sender (and possibly for the receiver).

With **Coinbase.Commerce**, a merchant can just make a dynamic charge and ask the customer to pay with crypto. You can read more about that here: https://github.com/bchavez/Coinbase.Commerce

I think, for your case, the **Coinbase.Commerce** is the more appropriate library to use.

Hope that helps.

Thanks,
Brian
