### ISSUE TITLE
404 Not Found on Sells Endpoint

### ISSUE THREAD

**Issue by astrohart** [bchavez/Coinbase#61]
Hi,
I am getting 
```
Call failed with status code 404 (Not Found): POST https://api.coinbase.com/v2/accounts/sells
```
from the server.  I run the following code (assume the params have been initialized correctly):
```
var sellTask = _client.Sells.PlaceSellOrderAsync(e.AccountId,
    placeSell, CancellationToken.None);
sellTask.Wait();
var sell = sellTask.Result;
```
I think Coinbase may have updated their REST API syntax and the code in this library has not been updated yet.  The docs say that the endpoint is:
```
POST https://api.coinbase.com/v2/accounts/**:account_id**/sells
```
I have a hunch that the code is not passing the account id.

**Comment by astrohart** [comment]
Nevermind.  I feel sheepish. Baaaaaa

Did not initialize the account id LOL

**Comment by bchavez** [comment]
Hm. Might be a good idea to have a null or empty string check here.
