### ISSUE TITLE
Error 404 when doing a TransferMoney

### ISSUE THREAD

**Issue by dgedise** [bchavez/Coinbase#64]
Hi! I'm programming a Small Application in VB.NET with coinbase DLL.
I want to convert my BTC currencies into ETH, and I use the TransferMoneyAsync function as follows:

    Private Sub Transfer_Coin (Origin As String, Destinity As String, Qty As Double)

        Dim config As New ApiKeyConfig With {
            .ApiKey = "XXXX",
            .ApiSecret = "YYYY"
        }
        Dim client As New CoinbaseClient(config)

        Dim c As New CreateTransfer With {
            .Type = "transfer",
            .To = adressdir(Destinity),
            .Amount = Qty,
            .Currency = Origin
        }

        Try
            Dim ResultTrans = client.Transactions.TransferMoneyAsync(adressdir(Origin,c))
            ResultTrans.Wait ()
            Dim a = ResultTrans.Result
            Debug.Write(a.Data.Status)
        Catch ex As Exception
        End Try

    End Sub

    EXAMPLE: Transfer_Coin("BTC","ETH",0.0005)

when I get to the accountlist.result step, it gives me an exception 404 - NOT FOUND. Maybe i'm doing something wrong?
I appreciate any idea. Tank you very much!

**Comment by bchavez** [comment]
Hi @dgedise ,

Thank you for your question. I suspect the 404 might have something to do with a `null` or `empty` parameter somewhere. Can you try to double-check for these when you call the `.TransferMoneyAsync` method?

Also, to help debug, try using **Fiddler** to debug the request. See this wiki page I created for help: https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler

Basically, once you have Fiddler up and running you'll need to call `client.EnableFiddlerDebugProxy("http://localhost.:8888")`. Then use Fiddler to inspect why the 404 is occurring.

Let me know what you find or if you need any more help.

Thanks,
Brian

**Comment by bchavez** [comment]
Hi @dgedise,

I haven't heard back in a while. I'm going to close the issue now, but please feel free to continue the conversation after the issue is closed with more diagnostic information from Fiddler.

Thanks,
Brian
