### ISSUE TITLE
Transfer between money accounts not possible

### ISSUE THREAD

**Issue by pazi77** [bchavez/Coinbase#66]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            |    5.1.2             |
| .NET Full Framework?   |      4.7.2           |
| Windows OS?              |          Win10        |
| Visual Studio?              |           2019       |

### What's the problem?
I try to transfer money from my bitcoin account to my etherium account. When i to this i get no exception but the response data are null. What i make wrong?
Now transfer of currency work in my fall. I alos tryed BTC to USDC.

I do this with follwing code:

CreateTransfer trans = new CreateTransfer();
trans.Amount = 1;
trans.Currency = "EUR";
trans.To = "accountID of ETH"

var transBTCToETC = await ApiClient.Transactions.TransferMoneyAsync("accountID of BTC",trans);

Also i have all permission in the api for this.
My Apikey and Secretkey also work. I can get my profile.

So what i make wrong by the transfer?

**Comment by bchavez** [comment]
`TransferMoney` is to transfer money between two accounts.

As the documentation reads below:

> Transfer bitcoin, bitcoin cash, litecoin or ethereum between two of a user’s accounts. Following transfers are allowed:
>
>wallet to wallet
>wallet to vault

IE:
* user1 BTC -> user2 BTC.
* user3 ETH -> user4 ETH

`TransferMoney` is not **conversion** of money (BTC -> ETH).

See for more information: https://developers.coinbase.com/api/v2#transfer-money-between-accounts
